name: base
dependencies:
  - python=3.6
  - pip=18
  - numpy
  - scipy
  - xarray
  - sympy
  - numba
  - pandas=0.23.4
  - xlrd     # excel-reader for pandas
  - openpyxl
  - seaborn
  - yaml
  - netCDF4
  - sqlite
  - requests
  - scrapy
  - beautifulsoup4
  - matplotlib
  - cartopy
  - scikit-learn
  - tensorflow
  - keras
  - qt
  - nose
  - jupyter
  - ipython=6.*
  - ipykernel=4.*
  - spyder
  - colorcet
  - sqlalchemy
  - opencv   # computer vision
  - graphviz # computer graphs
  - statsmodels    # statistical tools - from conda default channel
  - xlsxwriter     # pandas excel output
  - comtypes
  - nb_conda_kernels 
  - pydot
  - pip:
    - sphinx-rtd-theme
    - pygame
    - pymunk
    - salabim
    - nbextensions 
    - astral 
    - nbdime==1.0.3
    - autopep8
    - pyscaffold
    - python-docx
    - pyro4
    - pint
    - vtk
channels:
  - defaults
